### ISSUE TITLE
xgboost models to PMML for first N trees?

### ISSUE THREAD

**Issue by sjain777** [jpmml/r2pmml#16]
Hello, 
Is it possible to enhance the existing r2pmml to store the first N trees from an xgboost model?
This would be extremely useful when training a model using early_stopping, and then writing out the PMML for only the trees up to the best iteration. Thanks much in advance!

**Comment by vruusmann** [comment]
That would be trivial to implement. However, I might want to take some time to figure out a "generic parametrization/interface", which would be applicable to other boosting-type ensemble models (such as `gbm` or `lgbm.Booster`) as well.

Currently, you could write a small Java command-line application (based on the [JPMML-Model](https://github.com/jpmml/jpmml-model) library) to do the job. Its business logic would be the following:
```
PMML pmml = loadPMML(...);
MiningModel miningModel = (MiningModel)pmml.getModels(0);
Segmentation segmentation = miningModel.getSegmentation();
List<Segment> segments = segmentation.getSegments();
(segments.subList(n, segments.size())).clear(); // THIS
savePMML(pmml, ...);
```

**Comment by sjain777** [comment]
thanks much for your positive response! Looking forward for the next update to include this functionality.

**Comment by vruusmann** [comment]
The `r2pmml::xgb.Booster` function now has `ntreelimit` (the optimal number of trees - integer) and `compact` (apply tree compaction? - boolean) arguments.

**Comment by sjain777** [comment]
Thanks a lot!!


Sent from Yahoo Mail for iPhone


On Sunday, September 17, 2017, 2:29 PM, Villu Ruusmann <notifications@github.com> wrote:


The r2pmml::xgb.Booster function now has ntreelimit (the optimal number of trees - integer) and compact (apply tree compaction? - boolean) arguments.
