### ISSUE TITLE
regression xgboost model to pmml

### ISSUE THREAD

**Issue by LeZhengThu** [jpmml/r2pmml#18]
hello, I'm trying to convert a regression xgboost model to pmml format so there's no response_name or response_level in my model. Say the model is 'xgb', I use r2pmml(xgb, "input_ehr.pmml") and there comes out an error like this:
```
Error in shQuote(pmml_output) : 
argument "file" is missing, with no default
```
Can you help me with it? Thanks.

**Comment by LeZhengThu** [comment]
Hi, I got another error: java.lang.ClassCastException: org.jpmml.rexp.RDoubleVector cannot be cast to org.jpmml.rexp.RIntegerVector. Is this a fmap problem? What does the type variable mean in fmap? Thanks.

**Comment by vruusmann** [comment]
> I use r2pmml(xgb, "input_ehr.pmml")

The function `r2pmml.xgb.Booster` takes three positional arguments - `x`, `fmap` and `file`. You're only providing two of them.
