### ISSUE TITLE
pmml version control

### ISSUE THREAD

**Issue by LeZhengThu** [jpmml/r2pmml#21]
Hi, I've noticed that the package can convert r model to pmml 4.3. Now my platform can only support pmml 4.1. Therefore I wonder if I can convert r model to pmml 4.1 instead of 4.3? Thanks.

**Comment by vruusmann** [comment]
> Now my platform can only support pmml 4.1.

You should upgrade your platform.

If you don't want to upgrade your platform, then you can use older versions (some 1.2.X or 1.3.X version?) of the [`pmml` package](https://cran.r-project.org/package=pmml) to convert your R models to PMML.
