### ISSUE TITLE
R2pmml for xgboost not working

### ISSUE THREAD

**Issue by san1289** [jpmml/r2pmml#29]
Hi,

I was trying to execute your example for exporting an xgboost model and got the below error:

![image](https://user-images.githubusercontent.com/29946069/30367975-14228836-9870-11e7-998f-964383754856.png)

How can i resolve this

**Comment by vruusmann** [comment]
First, please update to the latest `r2pmml` package version (you're using JPMML-R 1.2.12 (released in January 2017), but the current one is 1.2.18).

Your screenshot does not contain any information about the conversion error. What is printed to the console after this "<truncated>" phrase?

**Comment by san1289** [comment]
I ran it using the latest version of the package and is still getting the same error. There is nothing printed to the console after truncated phase:

![image](https://user-images.githubusercontent.com/29946069/30369205-f2523be4-9873-11e7-8b7b-c20ab7782ec2.png)

**Comment by vruusmann** [comment]
In that case you need to disable output truncation. Or, depending on your R execution environment (RStudio perhaps?) the full exception stack trace might be available in R log file.

There is not a single bit of actionable information on your screenshot. Sure, I can see that you're using JPMML-R version 1.2.18 now, but that's all.

**Comment by vruusmann** [comment]
I have just re-installed the `r2pmml` package. Th example script given in its README file works fine:
https://github.com/jpmml/r2pmml#package-xgboost

Attached is the PMML document to prove it
[iris_xgb.pmml.txt](https://github.com/jpmml/r2pmml/files/1298985/iris_xgb.pmml.txt)
.
