### ISSUE TITLE
Urgent help required: Exporting reg:tweedie model using r2pmml

### ISSUE THREAD

**Issue by Adityam1992** [jpmml/r2pmml#32]
Hi Villu,

We are building a loss ratio model using xgboost in R. The distribution we are using is tweedie. We have built the model, however it seems r2pmml does not support tweedie. Could you please confirm that it indeed does not support tweedie. Is there any source present according to you, which can help in productionalizing this model.

We are in some serious peril here as this issue can compromise the whole project we are working on. Request you to take some time and respond to this e-mail as soon as you see this.

Thank you in advance!

Regards,
Aditya

**Comment by vruusmann** [comment]
Opened a new feature request under the JPMML-XGBoost project: https://github.com/jpmml/jpmml-xgboost/issues/20
