### ISSUE TITLE
Error generating PMML from xgboost model

### ISSUE THREAD

**Issue by rwking** [jpmml/r2pmml#33]
Hello,

I'm not sure if this is an issue with the r2pmml package, but I've tried troubleshooting my Java installation without any luck.

I'm trying to generate a pmml file from an xgboost model. I get the below error message when I try and I also get it when I run the sample code below.

```
library("ranger")
library("r2pmml")
data(iris)

iris.ranger = ranger(Species ~ ., data = iris, num.trees = 7, write.forest = TRUE)
print(iris.ranger)

r2pmml(iris.ranger, "iris_ranger.pmml", dataset = iris)
```

When executing this, I get the following error:

```
Error in .convert(tempfile, file, converter, converter_classpath, verbose) : 
  127
In addition: Warning message:
running command '"java" -cp "C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/guava-20.0.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/istack-commons-runtime-3.0.5.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/jaxb-core-2.3.0.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/jaxb-runtime-2.3.0.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/jcommander-1.48.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/jpmml-converter-1.2.6.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/jpmml-r-1.2.20.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/jpmml-xgboost-1.2.3.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/pmml-agent-1.3.8.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/pmml-model-1.3.8.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/pmml-model-metro-1.3.8.jar
C:/Users/rking/Documents/R/win-library/3.3/r2pmml/java/pmml-schema-1.3.8.jar
C:/Users/rking/Documents/R/win-library/3... <truncated>
```

Any help would be greatly appreciated. Thank you for developing this wonderful package.

Rich

**Comment by vruusmann** [comment]
> I get the below error message when I run the sample code below.

The provided sample code works beautifully on my computer. So, as you already suspect, there's something wrong with your computer (eg. the Java installation).

> When executing this, I get the following error:
> <truncated>

The detailed exception message appears to have been truncated. You should (re-)configure your R runtime to display exception messages in full length. Alternatively, you might try running the problematic R code using the vanilla R command-line executable, and capturing its standard error and output streams to a new file (and then paste its contents here).

R2PMML/JPMML-R require Java 1.7 or newer (that's a fairly lax requirement, given that almost all people are using Java 1.8 these days). What's your Java version?

**Comment by vruusmann** [comment]
Closing as invalid.
