### ISSUE TITLE
x-mathContext error in pmml import

### ISSUE THREAD

**Issue by aravind211** [jpmml/r2pmml#38]
Hi guys

I exported a pmml file for a reg:gamma (or count:poisson) Objective function within an xgboost model. When i tried importing this into one of our in-house deployment softwares, I am getting the following error:

![capture](https://user-images.githubusercontent.com/36885241/36725928-ebfd6c62-1bdd-11e8-9d3d-5268e3b3d98c.PNG)

**Comment by vruusmann** [comment]
Two choices, both on your end:
1. Use SAX filtering to remove the `x-mathContext` attribute.
2. Update your in-house deployment software to take advantage of this math context "hint" - it's mandatory to evaluate XGBoost models using 32-bits of precision (not the default 64-bits of precision).
