### ISSUE TITLE
"double" data type in xgboost pmml

### ISSUE THREAD

**Issue by Roniei** [jpmml/r2pmml#39]
The xgboost pmml is created with dataType="float"
Is there any option to change the dataType to be "double"?
Thanks

**Comment by vruusmann** [comment]
The underlying XGBoost library is using 32-bit floating point arithmetic.

Therefore, the PMML representation of XGBoost models must use `float` data type (not `double` data type) to ensure the reproducibility of predictions between XGBoost and (J)PMML.
