### ISSUE TITLE
Error with very large random forest.

### ISSUE THREAD

**Issue by cody-jor** [jpmml/r2pmml#44]
I've been trying to use your r2pmml package on github to transform a random forest into a pmml file. I've run into an error and I was wondering if this was a generalized problem, or something I'm doing wrong. I've included a screenshot of what my code looks like, as well as a glimpse of what my training data looks like. 
![screenshot 11](https://user-images.githubusercontent.com/41077697/42526714-713dd0c8-842b-11e8-975b-1472b3a4a745.png)

I've tried running the example code provided in the package with the iris data set, and it works fine. Any help would be appreciated.

**Comment by vruusmann** [comment]
You can solve `java.lang.OutOfMemoryError` by increasing JVM heap size:
https://github.com/jpmml/r2pmml#advanced-functionality
