### ISSUE TITLE
Support for multinomial gbm models

### ISSUE THREAD

**Issue by jtenini** [jpmml/r2pmml#5]
I can't tell if gbm models with a distribution type of "multinomial" are supported by this package. The package is creating pmml, but I can't tell how the trees are coupled to their class. 

For example, in modeling an variable with five classes I get a collection of trees with each tree modeling the probability of the output being one of the five classes.

> gbm.model.multi <- gbm(Y ~ .,
+                  data = dfmulti,
+                  distribution = "multinomial",
+                  n.trees = 1000,
+                  cv.folds = 0,
+                  interaction.depth = 8,
+                  n.minobsinnode = 1,
+                  shrinkage = .01
+ )

produces a model with 5000 trees, which I can export to PMML, but I can't tell which trees are modeling which class. Should I just reduce the segment id modulo 5?

**Comment by vruusmann** [comment]
The r2pmml package only supports binary classification models, where the probability of the `1` class is obtained by applying the logistic transform to the "raw" value.

It is nice to know that the package doesn't crash with multinomial classification models (although it probably should). Feel free to figure out how these 5000 trees should be partitioned, and what kind of transformation needs to be applied afterwards.

I believe that R implements multinomial GBM pretty much the same as Scikit-Learn, so technically it should be doable.

**Comment by vruusmann** [comment]
This feature has been implemented in https://github.com/jpmml/jpmml-r/commit/1caaa0741c4d9e17e1ebef08d05be9520fc7dc84
