### ISSUE TITLE
Conversion fails for xgboost with reg:gamma

### ISSUE THREAD

**Issue by Dan9ie** [jpmml/r2pmml#51]
Conversion fails when I try to build and export xgboost with objective as reg:gamma. 

xgb_ex <- xgb.train(params = list(booster = "gbtree", objective = "reg:gamma"), 
data = data.DMatrix, nround = 50)

r2pmml(xgb_ex, "check_sev.pmml", fmap = data.fmap)

But the same code works if I change the objective to reg:linear, retrain and export. Everything else being equal.

I am not pasting the entire log, but the point at which the error starts I think is :
Nov 06, 2018 3:30:37 PM org.jpmml.rexp.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: reg:gamma

I am using an older version of the r2pmml package, 0.13.1.

**Comment by vruusmann** [comment]
> I am using an older version of the r2pmml package, 0.13.1.

Please let's not open issues about historic r2pmml package versions!

The `reg:gamma` objective function is supported in the latest version, hence this issue is invalid.
