### ISSUE TITLE
Does this package support lightGBMs?

### ISSUE THREAD

**Issue by flippercy** [jpmml/r2pmml#75]
Hi @vruusmann:

Does this package support lightGBM models, please?

Thank you.

**Comment by vruusmann** [comment]
The R wrapper for LightGBM models is some weird & super complex class, which cannot be persisted using the standard `saveRDS()` function call.

Therefore, you must go use the manual workflow:
1. Train a LightGBM model in R
2. Save the LightGBM portion of this weird & complex object into a LGBM file using the `lgbm.save()` function: https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.save.html
3. Convert the LGBM file using the [JPMML-LightGBM](https://github.com/jpmml/jpmml-lightgbm) command-line application.

**Comment by vruusmann** [comment]
> The R wrapper for LightGBM models is some weird & super complex class, which cannot be persisted using the standard saveRDS() function call.

This issue might have been fixed in LightGBM version 4.0.0.

See https://github.com/microsoft/LightGBM/pull/4685 and https://github.com/microsoft/LightGBM/issues/4296

Reopening, as a reminder to re-evaluate the situation.
